# tasks/main.yml
---
- name: Ensure systemd service prerequisites {{ systemd_service_name }}
  ansible.builtin.import_tasks: prerequisites.yml

- name: Ensure systemd service {{ systemd_service_name }}
  ansible.builtin.import_tasks: systemd_service.yml
