# molecule/default/converge.yml
---
- name: Converge
  hosts: all

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        systemd_service_name: example
        systemd_service_reload: true
